name: flutter_fetch_post
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Need flutter packages get
  # Use use 0.11 because flutter_test not support.
  http: ^0.11.3+17
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
